//auth
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const SET_USER_DATA = "SET_USER_DATA";
export const SHOW_ALERT = "SHOW_ALERT";
export const REMOVE_ALL_ALERT = "REMOVE_ALL_ALERT";
export const LOG_OUT = "LOG_OUT";
export const UPDATE_ME = "UPDATE_ME";
export const SET_SPINNER = "SET_SPINNER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const AUTO_LOGIN = "AUTO_LOGIN";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
//tours
export const GET_ALL_TOURS = "GET_ALL_TOURS";
export const SET_TOURS_DATA = "SET_TOURS_DATA";
export const GET_TOUR = "GET_TOUR";
export const SET_TOUR = "SET_TOUR";
export const DELETE_TOUR = "DELETE_TOUR";
export const UPDATE_TOUR = "UPDATE_TOUR";
export const INSERT_NEW_TOUR = "INSERT_NEW_TOUR";
export const INSERT_TOUR_LOCATION = "INSERT_TOUR_LOCATION";
export const DELETE_TOUR_LOCATION = "DELETE_TOUR_LOCATION";
//reviews
export const SET_TOUR_REVIEWS = "SET_TOUR_REVIEWS";
export const GET_TOUR_REVIEWS = "GET_TOUR_REVIEWS";
export const GET_USER_REVIEWS = "GET_USER_REVIEWS";
export const SET_USER_REVIEWS = "SET_USER_REVIEWS";
export const UPDATE_USER_REVIEWS = "UPDATE_USER_REVIEWS";
export const DELETE_USER_REVIEWS = "DELETE_USER_REVIEWS";
export const INSERT_NEW_REVIEW = "INSERT_NEW_REVIEW";
export const GET_ALL_REVIEWS = "GET_ALL_REVIEWS";
export const SET_ALL_REVIEWS = "SET_ALL_REVIEWS";
export const DELETE_REVIEW = "DELETE_REVIEW";

//users
export const SET_USERS = "SET_USERS";
export const GET_USERS = "GET_USERS";
export const INSERT_NEW_USER = "INSERT_NEW_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const GET_GUIDES = "GET_GUIDES";
export const SET_GUIDES = "SET_GUIDES";

//bookings
export const GET_ALL_BOOKINGS = "GET_ALL_BOOKINGS";
export const SET_ALL_BOOKINGS = "SET_ALL_BOOKINGS";
export const GET_CHECKOUT_SESSION = "GET_CHECKOUT_SESSION";
export const SET_CHECKOUT_SESSION = "SET_CHECKOUT_SESSION";
export const GET_BOOKING = "GET_BOOKING";
export const SET_BOOKING = "SET_BOOKING";
export const UPDATE_BOOKING = "UPDATE_BOOKING";
export const DELETE_BOOKING = "DELETE_BOOKING";
export const GET_MY_BOOKINGS = "GET_MY_BOOKINGS";
export const SET_MY_BOOKINGS = "SET_MY_BOOKINGS";

//progress
export const SET_PROGRESS = "SET_PROGRESS";
export const RESET_PROGRESS = "RESET_PROGRESS";
